# # print("hello my lovable kiitian")
# # print("Pratik bohot bada bhadwa hai")
# # print("Pratik se zyada ",end="")
# # print("Madarchod koi nahin hai")
# # print("hellow world")
# fruit = []
# f1 = input("enter fruit name:")
# fruit.append(f1)
# f2 = input("enter fruit name:")
# fruit.append(f2)
# f3 = input("enter fruit name:")
# fruit.append(f3)
# f4 = input("enter fruit name:")
# fruit.append(f4)
# f4 = input("enter fruit name:")
# fruit.append(f4)
# f5 = input("enter fruit name:")
# fruit.append(f5)
# f6 = input("enter fruit name:")
# fruit.append(f6)
# f7 = input("enter fruit name:")
# fruit.append(f7)
# print(fruit) 
# def fact(n):
#     if ( n == 1 or n == 0):
#         return 1
#     return n * fact(n-1)

# n = int(input("enter a number :"))
# print(f"the factorial of a number is  : {fact(n)}")
f = open("file.txt")
data = f.read()
print(data)
f.close()